name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Update files and restart project
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          pass: ${{ secrets.REMOTE_PASSWORD }}
          connect_timeout: 10s
          script: |
            export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            cd /home/brenocarvalho
            touch a.txt
            echo $(nvm) >> a.txt 
            echo $(npm) >> a.txt 
            # cd ${{ secrets.REPOSITORY_DIR }}
            # pwd
            # whoami
            # git pull
            # npm run build
            # pm2 restart syslamarck-frontend
