name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Update files and restart project
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          pass: ${{ secrets.REMOTE_PASSWORD }}
          connect_timeout: 10s
          script: |
            cd ${{ secrets.REPOSITORY_DIR }}
            ./reload.sh
